version: "3.9"

services:
  dbstats:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${DBSTATS_USER}
      POSTGRES_PASSWORD: ${DBSTATS_PASSWORD}
      POSTGRES_DB: ${DBSTATS_DATABASE}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "127.0.0.1:55000:5432"
    volumes:
      - dbstats-data:/var/lib/postgresql/data

  dbusers01:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${DBUSERS01_USER}
      POSTGRES_PASSWORD: ${DBUSERS01_PASSWORD}
      POSTGRES_DB: ${DBUSERS01_DATABASE}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "127.0.0.1:55101:5432"
    volumes:
      - dbusers01-data:/var/lib/postgresql/data

  dbusers02:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${DBUSERS02_USER}
      POSTGRES_PASSWORD: ${DBUSERS02_PASSWORD}
      POSTGRES_DB: ${DBUSERS02_DATABASE}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "127.0.0.1:55102:5432"
    volumes:
      - dbusers02-data:/var/lib/postgresql/data

  dbusers03:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${DBUSERS03_USER}
      POSTGRES_PASSWORD: ${DBUSERS03_PASSWORD}
      POSTGRES_DB: ${DBUSERS03_DATABASE}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "127.0.0.1:55103:5432"
    volumes:
      - dbusers03-data:/var/lib/postgresql/data

volumes:
  dbstats-data:
  dbusers01-data:
  dbusers02-data:
  dbusers03-data:
